### ISSUE TITLE
Migration/Versions cause issues

### ISSUE THREAD

**Issue by bricknet1** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#9]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231364?module_item_id=541579

### Concern

When cloning this repo, it comes prepopulated with 2 files in the lib/migrations/versions directory, both of which appear to be db versions from the previous lesson, not this lesson (one of them is even labeled as "one-to-many" which is the previous canvas lesson). If you code along with the lesson, eventually you're asked to run:
alembic revision --autogenerate -m'Add User model'
This will trigger several errors because it appears to have trouble reconciling the previous versions. I had to delete both of those versions to get the alembic command to work correctly.

### Additional Context

The files can be found here: 
https://github.com/learn-co-curriculum/python-p3-sqlalchemy-many-to-many/tree/main/lib/migrations/versions

### Suggested Changes

Delete both files in the versions directory.

**Comment by professor-ben** [comment]
Starting on this now.

**Comment by professor-ben** [comment]
There were two issues here:

1. There were no instructions at the beginning of the lesson to run `alembic upgrade head`. This has been fixed.
2. A merge conflict warped the ID for the down revision in the second migration. This is fixed as well.

We still want the second out-of-the-box revision to be labeled "one-to-many" because it starts us where we left off in the one-to-many lesson. We also want to help y'all build confidence with picking up a project with previous migrations.

That being said, your fix is a good way to go about it if you run into this kind of error again. This was a very helpful issue to raise, so please raise another if you do run into something similar in the future!

Thanks,
Ben
